/* CADE OPS V2 - Hunt prototype. Self-contained tactical hunt layer. */

import { TEAM_ROSTER } from './teams.js';

const root = document.getElementById('scHunt');
const canvas = document.getElementById('huntCanvas');
if (!root || !canvas) throw new Error('CADE Hunt UI missing');
const ctx = canvas.getContext('2d');

const COLORS = { bg:'#141414', gold:'#FFA800', yellow:'#FFB514', white:'#FFFFFF', dim:'#8A8A8A', red:'#FF3D4F', green:'#3DC96B', blue:'#4CC9F0' };
const WORLD = { w:1600, h:900 };
const DURATION = 60;
const ROLES = {
  steve:{role:'CONTROLLER',color:'#FC8400',speed:115,range:150,detect:300,damage:1},
  gnar:{role:'BRUTE',color:'#00C2FF',speed:82,range:62,detect:270,damage:2},
  kosgood:{role:'ASSASSIN',color:'#FF2D9E',speed:155,range:52,detect:245,damage:1},
  scotty:{role:'TRACKER',color:'#8A8F98',speed:108,range:70,detect:420,damage:1},
  rookmate:{role:'RANGED',color:'#F0F024',speed:92,range:330,detect:310,damage:1},
  poppunk:{role:'DISRUPTOR',color:'#7DE8FF',speed:125,range:180,detect:340,damage:1}
};
const walls=[
  {x:360,y:90,w:280,h:34},{x:960,y:90,w:280,h:34},{x:360,y:776,w:280,h:34},{x:960,y:776,w:280,h:34},
  {x:360,y:170,w:34,h:210},{x:1206,y:170,w:34,h:210},{x:360,y:520,w:34,h:210},{x:1206,y:520,w:34,h:210},
  {x:650,y:220,w:300,h:34},{x:650,y:646,w:300,h:34},{x:650,y:254,w:34,h:160},{x:916,y:254,w:34,h:160},
  {x:650,y:486,w:34,h:160},{x:916,y:486,w:34,h:160}
];
const cover=[{x:170,y:220,w:110,h:70},{x:1320,y:220,w:110,h:70},{x:170,y:610,w:110,h:70},{x:1320,y:610,w:110,h:70},{x:740,y:390,w:120,h:120}];
const extraction={x:720,y:760,w:160,h:70};
const state={running:false,over:false,t:DURATION,score:0,mult:1,hunt:0,bestHunt:0,nerfs:0,close:0,damage:0,shots:0,abilities:0,extraction:false,intro:2.5,flash:0,shake:0,message:'',messageT:0,last:0,objective:'SURVIVE AND ESCAPE',player:{x:800,y:450,r:15,vx:0,vy:0,energy:100,hp:3,inv:0,ghost:0},keys:new Set(),mouse:{x:800,y:450,down:false},decoys:[],projectiles:[],particles:[],floaters:[],enemies:[],cooldowns:{rail:0,emp:0,decoy:0,ghost:0}};
const byId=id=>document.getElementById(id);
const hud={time:byId('huntTime'),score:byId('huntScore'),hunt:byId('huntMeter'),ability:byId('huntAbilities'),status:byId('huntStatus')};
function resize(){const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);}addEventListener('resize',resize,{passive:true});resize();
function scale(){const r=canvas.getBoundingClientRect();return{sx:r.width/WORLD.w,sy:r.height/WORLD.h};}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}function norm(x,y){const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d};}
function circleRect(c,r){const x=clamp(c.x,r.x,r.x+r.w),y=clamp(c.y,r.y,r.y+r.h);return Math.hypot(c.x-x,c.y-y)<c.r;}
function blocked(x,y,r){if(x-r<0||y-r<0||x+r>WORLD.w||y+r>WORLD.h)return true;const c={x,y,r};return walls.some(w=>circleRect(c,w));}
function moveBody(o,dx,dy){const nx=o.x+dx;if(!blocked(nx,o.y,o.r))o.x=nx;const ny=o.y+dy;if(!blocked(o.x,ny,o.r))o.y=ny;}
function lineBlocked(a,b){for(const w of walls)if(segmentRect(a,b,w))return true;return false;}
function segmentRect(a,b,r){const steps=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/18);for(let i=1;i<steps;i++){const t=i/steps,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h)return true;}return false;}
function addFloater(x,y,text,color=COLORS.gold,size=16){state.floaters.push({x,y,text,color,size,t:1});}function burst(x,y,color,n=10){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=50+Math.random()*260;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,t:.3+Math.random()*.5,c:color});}}
function say(text,c=COLORS.gold){state.message=text;state.messageT=1.3;addFloater(800,90,text,c,22);}
function spawnEnemy(id,x,y){const def=ROLES[id];state.enemies.push({id,x,y,r:20,vx:0,vy:0,state:'UNKNOWN',lastKnown:null,searchT:0,attackT:Math.random()*1.5,disabled:0,stun:0,age:0,def});}
function reset(){state.running=true;state.over=false;state.t=DURATION;state.score=0;state.mult=1;state.hunt=0;state.bestHunt=0;state.nerfs=0;state.close=0;state.damage=0;state.shots=0;state.abilities=0;state.extraction=false;state.intro=2.5;state.flash=0;state.shake=0;state.message='';state.messageT=0;state.objective='SURVIVE AND ESCAPE';Object.assign(state.player,{x:800,y:450,vx:0,vy:0,energy:100,hp:3,inv:0,ghost:0});state.decoys=[];state.projectiles=[];state.particles=[];state.floaters=[];state.enemies=[];Object.keys(state.cooldowns).forEach(k=>state.cooldowns[k]=0);spawnEnemy('steve',170,170);spawnEnemy('gnar',1430,170);spawnEnemy('kosgood',170,730);spawnEnemy('scotty',1430,730);spawnEnemy('rookmate',800,150);spawnEnemy('poppunk',800,750);say('HUNT STARTED');updateHUD();}
function show(){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('on'));root.classList.add('on');}
function start(){byId('huntEnd').classList.remove('show');reset();show();}
function finish(result){if(state.over)return;state.over=true;state.running=false;state.objective=result;burst(state.player.x,state.player.y,result==='ESCAPED'?COLORS.green:COLORS.red,36);byId('huntResult').textContent=result;byId('huntFinalScore').textContent=Math.round(state.score).toLocaleString();byId('huntFinalNerfs').textContent=state.nerfs;byId('huntFinalClose').textContent=state.close;byId('huntFinalTime').textContent=(DURATION-state.t).toFixed(1)+'s';byId('huntEnd').classList.add('show');}
function ability(name){if(!state.running||state.over||state.cooldowns[name]>0)return;const p=state.player;if(name==='rail'){state.cooldowns.rail=3.2;state.abilities++;state.shots++;const r=canvas.getBoundingClientRect(),s=scale(),wx=(state.mouse.x-r.left)/s.sx,wy=(state.mouse.y-r.top)/s.sy,n=norm(wx-p.x,wy-p.y);state.projectiles.push({x:p.x,y:p.y,vx:n.x*900,vy:n.y*900,t:1.2,r:8,kind:'rail'});addFloater(p.x,p.y-30,'RAIL SHOT');return;}if(name==='emp'){state.cooldowns.emp=6;state.abilities++;const radius=150;burst(p.x,p.y,COLORS.blue,26);for(const e of state.enemies)if(!e.disabled&&dist(p,e)<radius){e.stun=2.2;state.score+=500*state.mult;}state.hunt=Math.max(0,state.hunt-30);addFloater(p.x,p.y-30,'EMP BURST',COLORS.blue,18);return;}if(name==='decoy'){state.cooldowns.decoy=5;state.abilities++;const r=canvas.getBoundingClientRect(),s=scale(),wx=(state.mouse.x-r.left)/s.sx,wy=(state.mouse.y-r.top)/s.sy,a=Math.atan2(wy-p.y,wx-p.x);state.decoys.push({x:p.x+Math.cos(a)*100,y:p.y+Math.sin(a)*100,t:5,vx:Math.cos(a)*80,vy:Math.sin(a)*80});state.hunt=Math.max(0,state.hunt-25);addFloater(p.x,p.y-30,'DECOY',COLORS.yellow,18);return;}if(name==='ghost'){state.cooldowns.ghost=8;state.abilities++;p.ghost=2.2;p.inv=2.2;state.hunt=Math.max(0,state.hunt-40);burst(p.x,p.y,COLORS.gold,20);addFloater(p.x,p.y-30,'GHOST STEP',COLORS.gold,18);}}
function canSee(e,target){return dist(e,target)<=e.def.detect&&!lineBlocked(e,target);}function nearestDecoy(e){let best=null,bd=Infinity;for(const d of state.decoys){const dd=dist(e,d);if(dd<bd){bd=dd;best=d;}}return best;}
function enemyUpdate(e,dt){e.age+=dt;e.attackT=Math.max(0,e.attackT-dt);e.stun=Math.max(0,e.stun-dt);if(e.disabled>0){e.disabled-=dt;return;}if(e.stun>0)return;const p=state.player,target=p.ghost>0?null:p,dec=nearestDecoy(e),sees=target&&canSee(e,target),hears=dec&&dist(e,dec)<e.def.detect*.8;if(sees){e.state='HUNTING';e.lastKnown={x:p.x,y:p.y};e.searchT=3;state.hunt=clamp(state.hunt+dt*(e.id==='scotty'?10:6),0,100);}else if(hears){e.state='INVESTIGATING';e.lastKnown={x:dec.x,y:dec.y};e.searchT=2.5;}else if(e.searchT>0&&e.lastKnown){e.state='SEARCHING';e.searchT-=dt;}else{e.state='UNKNOWN';e.lastKnown=null;}state.bestHunt=Math.max(state.bestHunt,state.hunt);if(e.state==='HUNTING'){const n=norm(p.x-e.x,p.y-e.y);let speed=e.def.speed;if(e.id==='gnar'&&dist(e,p)<200)speed*=1.15;if(e.id==='kosgood'&&dist(e,p)>220)speed*=1.2;if(state.extraction&&e.id==='steve')speed*=1.18;moveBody(e,n.x*speed*dt,n.y*speed*dt);if(dist(e,p)<e.def.range+e.r+p.r&&e.attackT<=0){damagePlayer(e.def.damage);e.attackT=e.id==='gnar'?2:1.25;}}else if(e.state==='INVESTIGATING'||e.state==='SEARCHING'){const n=norm((e.lastKnown?.x||e.x)-e.x,(e.lastKnown?.y||e.y)-e.y);moveBody(e,n.x*e.def.speed*.72*dt,n.y*e.def.speed*.72*dt);}else{const a=e.age*.25+e.id.length;moveBody(e,Math.cos(a)*e.def.speed*.25*dt,Math.sin(a*1.3)*e.def.speed*.25*dt);}if(e.id==='rookmate'&&e.state==='HUNTING'&&e.attackT<=0&&dist(e,p)<e.def.range&&!lineBlocked(e,p)){e.attackT=2.6;const n=norm(p.x-e.x,p.y-e.y);state.projectiles.push({x:e.x,y:e.y,vx:n.x*500,vy:n.y*500,t:2,r:7,kind:'enemy'});}if(e.id==='poppunk'&&e.state==='HUNTING'&&Math.random()<dt*.4)state.decoys.push({x:p.x,y:p.y,t:1.5,vx:0,vy:0,enemy:true});}
function damagePlayer(n){const p=state.player;if(p.inv>0)return;p.hp=Math.max(0,p.hp-n);p.inv=1;state.damage+=n;state.mult=Math.max(1,state.mult*.72);state.hunt=clamp(state.hunt+18,0,100);state.shake=10;burst(p.x,p.y,COLORS.red,20);if(p.hp<=0)finish('WIPED');}
function playerUpdate(dt){const p=state.player;p.inv=Math.max(0,p.inv-dt);p.ghost=Math.max(0,p.ghost-dt);let x=0,y=0;if(state.keys.has('w')||state.keys.has('arrowup'))y--;if(state.keys.has('s')||state.keys.has('arrowdown'))y++;if(state.keys.has('a')||state.keys.has('arrowleft'))x--;if(state.keys.has('d')||state.keys.has('arrowright'))x++;if(x||y){const n=norm(x,y),speed=p.ghost>0?390:300;p.vx=n.x*speed;p.vy=n.y*speed;moveBody(p,p.vx*dt,p.vy*dt);}else{p.vx*=.8;p.vy*=.8;}if(p.inv<=0&&p.ghost<=0)state.hunt=Math.max(0,state.hunt-dt*2.3);}
function projectilesUpdate(dt){for(let i=state.projectiles.length-1;i>=0;i--){const q=state.projectiles[i];q.t-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;if(q.t<=0||blocked(q.x,q.y,q.r)){state.projectiles.splice(i,1);continue;}if(q.kind==='rail'){let hit=false;for(const e of state.enemies)if(!e.disabled&&dist(q,e)<e.r+q.r){e.disabled=2.8;state.nerfs++;state.score+=1800*state.mult;state.mult+=.35;state.hunt=Math.max(0,state.hunt-22);burst(e.x,e.y,ROLES[e.id].color,25);addFloater(e.x,e.y-25,'NERFED',COLORS.green,20);hit=true;break;}if(hit)state.projectiles.splice(i,1);}else if(dist(q,state.player)<q.r+state.player.r){damagePlayer(1);state.projectiles.splice(i,1);}}}
function decoysUpdate(dt){for(let i=state.decoys.length-1;i>=0;i--){const d=state.decoys[i];d.t-=dt;d.x+=d.vx*dt;d.y+=d.vy*dt;if(d.t<=0)state.decoys.splice(i,1);}}
function particlesUpdate(dt){for(const p of state.particles){p.t-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;}state.particles=state.particles.filter(p=>p.t>0);for(const f of state.floaters){f.t-=dt;f.y-=20*dt;}state.floaters=state.floaters.filter(f=>f.t>0);}
function update(dt){state.t-=dt;state.flash=Math.max(0,state.flash-dt*2);state.shake=Math.max(0,state.shake-dt*25);state.messageT=Math.max(0,state.messageT-dt);for(const k in state.cooldowns)state.cooldowns[k]=Math.max(0,state.cooldowns[k]-dt);playerUpdate(dt);decoysUpdate(dt);for(const e of state.enemies)enemyUpdate(e,dt);projectilesUpdate(dt);particlesUpdate(dt);state.score+=dt*(35+state.hunt*.7)*state.mult;state.mult+=dt*(state.hunt>70?.08:.025);if(state.t<=10&&!state.extraction){state.extraction=true;state.objective='EXTRACTION OPEN';say('EXTRACTION OPEN',COLORS.green);}if(state.extraction&&state.t<=0){if(state.player.x>extraction.x&&state.player.x<extraction.x+extraction.w&&state.player.y>extraction.y&&state.player.y<extraction.y+extraction.h)finish('ESCAPED');else finish('MISSED EXTRACTION');}if(state.extraction&&circleRect(state.player,extraction)&&state.t>0)state.score+=dt*2000*state.mult;updateHUD();}
function updateHUD(){if(!hud.time)return;hud.time.textContent=Math.max(0,state.t).toFixed(1);hud.score.textContent=Math.round(state.score).toLocaleString();hud.hunt.querySelector('.hunt-fill').style.width=state.hunt+'%';hud.ability.innerHTML=['rail','emp','decoy','ghost'].map((k,i)=>`<div class="hunt-ability ${state.cooldowns[k]>0?'cooling':''}"><b>${i+1}</b><span>${k.toUpperCase()}</span><em>${state.cooldowns[k]>0?state.cooldowns[k].toFixed(1):'READY'}</em></div>`).join('');hud.status.textContent=state.objective;}
function drawEnemy(e){const role=ROLES[e.id];ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=role.color;ctx.shadowColor=role.color;ctx.shadowBlur=e.state==='HUNTING'?22:8;ctx.beginPath();ctx.arc(0,0,e.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#141414';ctx.font='900 10px ui-monospace,monospace';ctx.textAlign='center';ctx.fillText(e.id.toUpperCase(),0,4);ctx.strokeStyle=e.state==='HUNTING'?COLORS.red:role.color;ctx.lineWidth=e.state==='HUNTING'?3:1;ctx.beginPath();ctx.arc(0,0,e.r+7,0,Math.PI*2);ctx.stroke();ctx.restore();}
function draw(){const r=canvas.getBoundingClientRect(),s=scale();ctx.save();ctx.clearRect(0,0,r.width,r.height);ctx.scale(s.sx,s.sy);if(state.shake)ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);ctx.fillStyle=COLORS.bg;ctx.fillRect(0,0,WORLD.w,WORLD.h);ctx.strokeStyle='rgba(255,168,0,.045)';ctx.lineWidth=1;for(let x=0;x<WORLD.w;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.h);ctx.stroke();}for(let y=0;y<WORLD.h;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.w,y);ctx.stroke();}for(const w of walls){ctx.fillStyle='#232323';ctx.fillRect(w.x,w.y,w.w,w.h);ctx.strokeStyle='rgba(255,168,0,.22)';ctx.strokeRect(w.x,w.y,w.w,w.h);}for(const c of cover){ctx.fillStyle='#2D2D2D';ctx.fillRect(c.x,c.y,c.w,c.h);ctx.strokeStyle='rgba(255,255,255,.09)';ctx.strokeRect(c.x,c.y,c.w,c.h);}if(state.extraction){ctx.fillStyle='rgba(61,201,107,.14)';ctx.fillRect(extraction.x,extraction.y,extraction.w,extraction.h);ctx.strokeStyle=COLORS.green;ctx.lineWidth=3;ctx.strokeRect(extraction.x,extraction.y,extraction.w,extraction.h);ctx.fillStyle=COLORS.green;ctx.font='900 22px Bungee,Arial';ctx.textAlign='center';ctx.fillText('EXTRACT',800,803);}for(const e of state.enemies){if(e.disabled>0)ctx.globalAlpha=.25;drawEnemy(e);ctx.globalAlpha=1;}for(const d of state.decoys){ctx.globalAlpha=Math.min(1,d.t);ctx.strokeStyle=d.enemy?COLORS.red:COLORS.yellow;ctx.lineWidth=3;ctx.beginPath();ctx.arc(d.x,d.y,18+Math.sin(d.t*8)*4,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}for(const q of state.projectiles){ctx.strokeStyle=q.kind==='rail'?COLORS.gold:COLORS.red;ctx.lineWidth=q.kind==='rail'?5:4;ctx.beginPath();ctx.moveTo(q.x-q.vx*.025,q.y-q.vy*.025);ctx.lineTo(q.x,q.y);ctx.stroke();}const p=state.player;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle=p.ghost>0?'rgba(255,168,0,.35)':COLORS.gold;ctx.shadowColor=COLORS.gold;ctx.shadowBlur=18;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=COLORS.white;ctx.lineWidth=2;ctx.stroke();ctx.restore();for(const p of state.particles){ctx.globalAlpha=Math.max(0,p.t*2);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,2.5,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}for(const f of state.floaters){ctx.globalAlpha=Math.min(1,f.t*2);ctx.fillStyle=f.color;ctx.font=`900 ${f.size}px Bungee,Arial`;ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y);ctx.globalAlpha=1;}ctx.restore();if(state.intro>0&&state.running){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(0,0,r.width,r.height);ctx.fillStyle=COLORS.gold;ctx.font='900 38px Bungee,Arial';ctx.textAlign='center';ctx.fillText('YOU ARE BEING HUNTED',r.width/2,r.height/2);}if(state.over){ctx.fillStyle='rgba(0,0,0,.68)';ctx.fillRect(0,0,r.width,r.height);}ctx.restore();}
function loop(now){const dt=Math.min(.05,(now-(state.last||now))/1000);state.last=now;if(state.running&&!state.over){state.intro=Math.max(0,state.intro-dt);update(dt);}draw();requestAnimationFrame(loop);}requestAnimationFrame(loop);
addEventListener('keydown',e=>{if(!root.classList.contains('on'))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){state.keys.add(k);e.preventDefault();}if(['1','2','3','4'].includes(k)){ability(['rail','emp','decoy','ghost'][+k-1]);e.preventDefault();}if(k==='escape'){finish('ABORTED');e.preventDefault();}},{passive:false});
addEventListener('keyup',e=>{if(!root.classList.contains('on'))return;state.keys.delete(e.key.toLowerCase());});canvas.addEventListener('mousemove',e=>{state.mouse.x=e.clientX;state.mouse.y=e.clientY;});canvas.addEventListener('mousedown',e=>{if(e.button===0){state.mouse.down=true;ability('rail');}});canvas.addEventListener('mouseup',()=>state.mouse.down=false);
byId('btnHuntV2').addEventListener('click',()=>{byId('huntEnd').classList.remove('show');show();});
byId('huntStart').addEventListener('click',start);byId('huntBack').addEventListener('click',()=>{root.classList.remove('on');document.getElementById('scTitle')?.classList.add('on');});byId('huntAgain').addEventListener('click',()=>{byId('huntEnd').classList.remove('show');start();});byId('huntHome').addEventListener('click',()=>{byId('huntEnd').classList.remove('show');root.classList.remove('on');document.getElementById('scTitle')?.classList.add('on');});for(const [id,k] of [['huntA1','rail'],['huntA2','emp'],['huntA3','decoy'],['huntA4','ghost']])byId(id)?.addEventListener('pointerdown',e=>{e.preventDefault();ability(k);});
window.CADE_HUNT_V2={start,reset,state};
